query GetAllAddresses($customerId: String!) {
  getAllAddresses(customerId: $customerId) {
    id
    customerId
    addressLine1
    addressLine2
    city
    state
    postalCode
    country
    isDefault
  }
}