query GetCart {
  getCartItems {
    variantInfo {
      id
      variantName
      color
      size
      price
      discType
      discValue
      stockQuantity
      status
      product {
      id    
      }
    }
    discType
    discValue
    finalPrice
    id
    image
    price
    productId
    productName
    quantity
    variantId
  }
}