query GetMyOrders($pagination: PaginationInput!) {
  getMyOrders(pagination: $pagination) {
    data {
      customerName
      createdAt
      id
      orderId
      invoiceNo
      addressId
      transactionId
      paymentMode
      totalAmount
      status
      transactionType
      addressData {
        id
        customerId
        addressLine1
        addressLine2
        city
        state
        postalCode
        country
        isDefault
      }
    }
    totalCount
    currentPage
    totalPages
  }
}