query SingleProduct($singleProductId: String!) {
  singleProduct(id: $singleProductId) {
    id
    productName
    skuCode
    description
    status
    brandId
    categoryId
    subCategoryId
    materialId
    patternId
    vendorId
    purchasePrice
    salePrice
    primaryImage
    images {
      id
      imageUrl
      product {
        id
      }
    }
    variants {
      id
      variantName
      color
      size
      price
      discType
      discValue
      stockQuantity
      status
      product {
        id
      }
    }
    brandName
    categoryName
    materialName
    patternName
    newArrival
    featured
  }
}